# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://github.com/combateafraude/iOS.git'
source 'https://cdn.cocoapods.org/'
target 'CafFaceLiveness' do
 # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!
 pod 'FaceLiveness', '~> 3.1.9'
 # Pods for RnIos

end
